# Generated by Django 4.2.5 on 2023-10-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('rubro', models.CharField(max_length=15)),
                ('matricula', models.CharField(max_length=15)),
                ('dni', models.IntegerField(max_length=15)),
                ('edad', models.IntegerField(default=0, max_length=15)),
                ('domicilio', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
